name: Build RPM from spec file

on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      spec_file:
        description: "Path to the .spec file"
        required: true
        default: 'contrib/rhel/7/SPECS/*.spec'
        type: string
      additional_repos:
        description: "List of additional repos"
      who-to-greet:
        description: "Name to greet"
        required: true
        default: "Josa"
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build RPM
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Validate
        id: validate
        run: |
          echo "# Environment"
          env | sort
          echo
          echo "# working directory (pwd)"
          pwd
          echo
          echo "# listing all files"
          ls -lR
          echo
          echo "spec_file=$RANDOM" >> $GITHUB_OUTPUT
      - name: set variable
        run: |
          echo "# Environment"
          env | grep -i spec
          if [ -z "${SPEC_FILE}" ] ; then
            SPEC_FILE=$(find . -name "*.spec" | head -1 | sed 's#./##')
          fi
      - name: List
        run: |
          echo "# Environment"
          env | sort
          echo
          echo "# working directory (pwd)"
          pwd
          ls -lR

      # Change @main to a specific commit SHA or version tag, e.g.:
      # actions/hello-world-docker-action@e76147da8e5c81eaf017dede5645551d4b94427b
      # actions/hello-world-docker-action@v1.2.3
      - name: Build RPM in Docker Action
        id: build-rhel-8
        uses: EWBr0wn/hello-world-docker-action@rockylinux-dev
        with:
          spec_file: ${{ inputs.spec_file }}
          additional_repos: ${{ inputs.additional_repos }}
          who-to-greet: ${{ inputs.who-to-greet }}
